Project 4
Nick-552/java-course-2023 pull request #15
Opened 2023-12-10 20:57 UTC by Nick-552

2023-12-10 23:24 UTC, Nick-552 commented
![image3b41c7da-a09c-4d43-ac5a-32f5aa34b2f5](https://github.com/Nick-552/java-course-2023/assets/115263760/93c76472-ea91-4adb-9d22-cda6de71a323)
![image4a30320e-7d1f-4fb8-bb9d-bf784090c0e2](https://github.com/Nick-552/java-course-2023/assets/115263760/7d957625-6466-4d32-a8ca-87763694b869)
![image9cb614b4-c956-4d7d-97d4-ce6029188cc8](https://github.com/Nick-552/java-course-2023/assets/115263760/781c16ae-b6fe-40f7-bba7-8d972b77aa46)
![image037e865a-1dfe-4a21-8be1-8108250db34d](https://github.com/Nick-552/java-course-2023/assets/115263760/c5e4ab75-a655-4914-897d-5f93aa70078d)
![imagea793c55c-ee31-4671-b64d-c7928fa6f0db](https://github.com/Nick-552/java-course-2023/assets/115263760/47fbae2c-402a-4af9-9888-e5feb8819fd2)
![imagea8858038-8d4e-47ea-a8cf-e2a67d422bde](https://github.com/Nick-552/java-course-2023/assets/115263760/7f0569a7-44ce-45b6-b118-5a6c1776707f)
![imagead26e931-c80c-4b8d-8af7-b67165aaf7b9](https://github.com/Nick-552/java-course-2023/assets/115263760/82b0bf79-97fe-4749-86a9-904f948ac6fe)
![imageb01b76a7-c582-473d-a604-6a02350c89bd](https://github.com/Nick-552/java-course-2023/assets/115263760/8fdb9ed1-9555-47d7-a7ff-8442daaecf1d)
![imagee8f4aab5-9303-4f7a-9f69-dbd9c6a524c9](https://github.com/Nick-552/java-course-2023/assets/115263760/77b10569-fd69-4a2e-98c7-a75184eeee13)
![imagef47d9e00-ac46-409f-9344-f9106e064e76](https://github.com/Nick-552/java-course-2023/assets/115263760/98415758-b427-4232-828b-ae4b67ef1437)
![imagef6903e98-df41-4b55-a3d1-8f8b18cb0771](https://github.com/Nick-552/java-course-2023/assets/115263760/df701393-677a-4427-9433-b1b5fd7c3fc1)

2023-12-10 23:58 UTC, Nick-552 commented
# Реализован генератор т.н. фрактального пламени или фрактальных искр. 
### Реализованы классы `DefaultRenderer` и `ParallelRenderer` для однопоточной и многопоточной генерации **цветных** изображений фракталов. Генерация изображений полностью настраиваемая:
Пользователь может настроить следующие параметры:
 - разрешение изображения
 - список нелинейных трансформаций
 - параметр симметрии
 - параметр гамма коррекции
 - количество сэмплов
 - количество итераций на сэмпл
 - размеры `Rectangle` (влияет на попадание на картинку узоров)
 ### Реализованы следующие нелинейные трансформации:
  - `DiscTransformation`
  - `ExponentialTransformation`
  - `EyefishTransformation`
  - `HandkerchiefTransformation`
  - `JuliaTransformation`
  - `PowerTransformation`
  - `SinusoidalTransformation`
  - `SphericalTransformation`
  - `SpiralTransformation`
  - `SwirlTransformation`
### Реализована постобработка изображения с помощью алгоритма гамма коррекции.
### Реализован utility класс для записи изображения на диск, а также вспомогательные классы и классы модели приложения, такие как:
 - `ImageFormat`
 -  `ListUtils`
 -  `AffineTransformation`
 -  `AffineTransformationCoefficients`
 -  `Color`
 -  `FractalImage`
 -  `Pixel`
 -  `Point`
 -  `Rectangle`
 ### Также, несмотря на то, что изображения были отправлены на оценку глубокой ночью,  за небольшой период времени были получены положительные отзывы о проделанной работе
![image](https://github.com/Nick-552/java-course-2023/assets/115263760/9b20644c-2d98-43a6-8b0d-f8e3b5a4eb3f)

2023-12-11 10:02 UTC, Nick-552 commented
Тесты напишу в скором времени, хотя для некоторых классов не особо понимаю как протестировать.

2023-12-17 11:51 UTC, SHvatov commented on src/main/java/edu/project4/renderer/AbstractRenderer.java
> +        Rectangle world,
На будущее - есть хорошее правило, что когда у метода слишком много параметров, или есть вероятность того, что они будут или уже часто меняются (их набор и кол-во), то лучше их объединить в ДТОху, и работать уже с ней. Гораздо проще, чем потом по всему коду бегать и менять вызовы метода из-за изменения его сигнатуры.

2023-12-17 11:51 UTC, SHvatov requested changes
@Nick-552 👍, ждем тестов)

2023-12-18 20:32 UTC, Nick-552 commented
Добавил тесты

2023-12-19 15:59 UTC, SHvatov approved these changes
@Nick-552 👍, можно мержить)

_4 из 4 заданий выполнено_

2023-12-19 16:00 UTC, SHvatov approved these changes

2023-12-19 16:00 UTC, SHvatov commented
@Nick-552 я аппрувнул, но Гитхабу этого мало(

2023-12-19 16:01 UTC, merged

2023-12-19 16:18 UTC, Nick-552 commented
> @Nick-552 я аппрувнул, но Гитхабу этого мало(

Видимо github хочет чтобы аппрувнул collaborator with admin, owner, or write access to the repository. То есть она будет работать нормально только если Вы будете коллаборатором. В любом случае, у меня, как у владельца репозитория есть права мерджить без аппрувов и ревью.